{% set name = "renumerate" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21efc7303b1bc9b829c5473fb4713a5a0e682e626e98511a963d61f48a2873ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.3
    - packaging >=24.2.0
    - tox >=4.24.2
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=77.0.3
    - pkg-about >=1.2.11

test:
  imports:
    - renumerate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpierz/renumerate
  doc_url: https://renumerate.readthedocs.io/
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
