{% set python_min = python_min|default("0.1a0") %}
{% set name = "renumerate" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/renumerate-{{ version }}.zip
  sha256: 98805446a560b419c120fb2eef9b85ebaf6a5d091a5f49a192780ebe0b692c38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=75.5.0
    - wheel >=0.44.0
    - packaging >=24.1.0
    - tox >=4.23.2
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=75.1.0
    - pkg-about >=1.2.5

test:
  imports:
    - renumerate
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/karpierz/renumerate
  doc_url: https://renumerate.readthedocs.io/
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
