{% set name = "renumerate" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 361fd871ee0224fb402b16def6b05bba2a899645317ab3210f20406c1b793531

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.6.0
    - packaging >=24.2.0
    - tox >=4.23.2
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=75.6.0
    - pkg-about >=1.2.6

test:
  imports:
    - renumerate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpierz/renumerate
  doc_url: https://renumerate.readthedocs.io/
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
