{% set name = "renumerate" %}
{% set version = "1.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/renumerate-{{ version }}.zip
  sha256: ba0d62e758083b13008fd9419547ea112d7049cd06a9edcc2f55dc344e65c42c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.1,<4.0.0
    - setuptools >=68.2.2
    - wheel >=0.42.0
    - packaging >=23.2.0
    - tox >=4.11.3
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - setuptools >=68.2.2
    - pkg-about >=1.1.5

test:
  imports:
    - renumerate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/karpierz/renumerate
  doc_url: https://renumerate.readthedocs.io/
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
