{% set name = "renumerate" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91165fd8dac878321c4aebe10fa80f698ac1b4b02af6bb0ac9198e725948a12d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.8.0
    - packaging >=24.2.0
    - tox >=4.24.1
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=75.8.0
    - pkg-about >=1.2.9
test:
  imports:
    - renumerate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpierz/renumerate
  doc_url: https://renumerate.readthedocs.io/
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
