{% set name = "renumerate" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/renumerate-{{ version }}.zip
  sha256: ac0fa491d02d6116b3376c5e86f93a5e7d8423fb42a7c0ba64299dd22c1a00c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9.0,<4.0.0
    - setuptools >=75.1.0
    - wheel >=0.44.0
    - packaging >=24.1.0
    - tox >=4.21.2
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - setuptools >=75.1.0
    - pkg-about >=1.2.1

test:
  imports:
    - renumerate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/karpierz/renumerate
  doc_url: https://renumerate.readthedocs.io/
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
