schema_version: 1

context:
  name: renumerate
  version: "2.0.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7ea06336eb704e62e3ba7e9811ed76a43cbb39173f38fa4b96f2949377c9a95c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80.9.0
    - packaging >=25.0.0
    - tox >=4.32.0
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools >=80.9.0
    - typing_extensions >=4.15.0
    - pkg-about >=2.0.0

tests:
  - python:
      imports:
        - renumerate
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE
  homepage: https://github.com/karpierz/renumerate
  documentation: https://renumerate.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
