schema_version: 1

context:
  name: renumerate
  version: "2.4.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c4afc4ee36bad667ca49c2f6157602f46d0ba8a9401a6601ea1b46f1b16f202e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=81.0.0
    - packaging >=26.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools >=81.0.0
    - typing_extensions >=4.15.0
    - pkg-about >=2.3.0

tests:
  - python:
      imports:
        - renumerate
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE
  homepage: https://github.com/karpierz/renumerate
  documentation: https://renumerate.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
