schema_version: 1

context:
  name: renumerate
  version: "2.4.4"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: fa168780dea4b6b1481d5ba33a1dc380051c9a00f7918c712f354ff4a772e2a2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=81.0.0
    - packaging >=26.3.0
    - pip
  run:
    - python >=${{ python_min }}
    - typing-extensions >=4.16.0
    - pkg-about >=2.4.0

tests:
  - python:
      imports:
        - renumerate
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Reverse enumerate.
  license: Zlib
  license_file: LICENSE
  homepage: https://github.com/karpierz/renumerate
  documentation: https://renumerate.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
